#define aNUL 0 //nul \0 delimeter
#define aSOH 1 //start of header
#define aSTX 2 //start of text
#define aETX 3 //end of text
#define aEOT 4 //end of transmission
#define aENQ 5
#define aACK 6 //affirm acknowledge
#define aBEL 7 //audible bell
#define aBS 8 //backspace
#define aTAB 9 //horizontal tab
#define aLF 10 //line feed
#define aVT 11 //verticle tab
#define aFF 12 //form feed
#define aCR 13 //carriage return
#define aSO 14 //shift out
#define aSI 15 //shift in
#define aDCE 16 //data link escape3
#define aDC1 17
#define aDC2 18
#define aDC3 19
#define aDC4 20
#define aNAK 21 //negative acknowledge
#define aSYN 22 //synchronous idle
#define aETB 23 //end of transmission
#define aCAN 24 //cancel
#define aEM 25//end of medium
#define aSUB 26 //Substitute
#define aESC 27 //Escape
#define aFS 28 //File separator
#define aGS 29 //Group separator
#define aRS 30 //Record separator
#define aUS 31 //unlinked separator
#define aSPC 32 //Space

#define aCODE 94 //character for printer command
#define aHCR aEOT // hard carriage return
#define aITALIC 'I' //Italics Toggle
#define aCENTER 'C' // to center line
#define aDOUBLE 'D' //Double strike the toggle
#define aEXPAND 'E' //Emphasize toggle
#define aSUPERS 'S' //superscript toggle
#define aBOLD 'B' //Bold Toggle
#define aTRUE 1 //True
#define aFALSE 2 //False
